#!/bin/bash
# Make Qt aware of bundled fonts
export QT_FONTDIR="$APPDIR/usr/share/fonts/truetype"

# Run your binary
HERE="$(dirname "$(readlink -f "$0")")"
exec "$HERE/usr/bin/python_postar_gui" "$@"
